default: true

# Allow first-line headings to be optional due to special needs of profile section
first-line-heading: false

# Some services use a linebreak-sensitive renderer, e.g. GitHub comment and BitBucket
line-length: false

no-trailing-punctuation:
  # Allow headings to end with question mark for FAQ
  punctuation: ".,;:"

# Prettier handles these:
list-marker-space: false
no-multiple-blanks: false
