apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
      - name: from-build-pack
        resources: {}
        taskSpec:
          metadata: {}
          stepTemplate:
            env:
              - name: NPM_CONFIG_USERCONFIG
                value: /tekton/home/npm/.npmrc
            image: uses:jenkins-x/jx3-pipeline-catalog/tasks/javascript-ui-nginx/pullrequest.yaml@versionStream
            name: ""
            resources:
              limits: {}
            workingDir: /workspace/source
          steps:
            - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone-pr.yaml@versionStream
              name: ""
              resources: {}
            - name: jx-variables
              resources: {}
            - image: node:14-slim
              name: build-npm-install
              resources: {}
              script: |
                #!/bin/sh
                # Use perm flag to stop "cannot run in wd" issue
                npm set unsafe-perm true
                npm install
            - image: node:14-slim
              name: build-npm-test
              resources: {}
              script: |
                #!/bin/sh
                CI=true DISPLAY=:99 npm test
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}
